# Importing necessary libraries

In [1]:
#Let's Import required Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

#Let's Import selenium webdriver 
from selenium import webdriver

#Let's Import required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotInteractableException

#Let's Import requests
import requests

#Let's Importing regex
import re

#Let's Import support drivers
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

#Let's Import Time Out Exception
from selenium.common.exceptions import TimeoutException
from datetime import datetime

#Let's Suppress warnings for a clean notebook
import warnings
warnings.filterwarnings('ignore')

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
    
A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [3]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-3-f6f558244406>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [4]:
url =  'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [5]:
num =[]
vid =[]
uploadr = []
views = []
date = []

In [6]:
for i in range(1,31):
    num_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
    try:
      num.append(num_tag.text)
    except NoSuchElementException:
      num.append("-")

<ipython-input-6-b9fc5a678906>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  num_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")

In [7]:
for i in range(1,31):
    vid_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
    try:
        vid.append(vid_tag.text.strip().split('"')[1]) #appending only the names of the videos
    except NoSuchElementException:
        vid.append("-")

<ipython-input-7-3e2fb0c85eba>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  vid_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")

In [8]:
for i in range(1,31):
    uploadr_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
    try:
        uploadr.append(uploadr_tag.text)
    except NoSuchElementException:
        uploadr.append("-")

<ipython-input-8-7d7906784f7e>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  uploadr_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")

In [9]:
for i in range(1,31):
    views_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
    try:
        views.append(views_tag.text)
    except NoSuchElementException:
        views.append("-")

<ipython-input-9-90734d97cbe8>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  views_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")

In [10]:
for i in range(1,31):
    date_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")
    try:
        date.append(date_tag.text)
    except NoSuchElementException:
        date.append("-")

<ipython-input-10-4cea6792710c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  date_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")

In [11]:
topyoutubevids = {"Rank":num,"Name":vid,"Artist":uploadr,"Upload Date":date,"Views(Billions)":views}
topyoutubevidsDF = pd.DataFrame(topyoutubevids)
topyoutubevidsDF

,Rank,Name,Artist,Upload Date,Views(Billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.95
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.69
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.08
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.58
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.38
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.82
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.54
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.48
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.42
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.39
10,11.,Gangnam Style,Psy,"July 15, 2012",4.30
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.79
12,13.,Sugar,Maroon 5,"January 14, 2015",3.62
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.50
14,15.,Roar,Katy Perry,"September 5, 2013",3.50
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.48
16,17.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.46
17,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.38
18,19.,Girls Like You,Maroon 5,"May 31, 2018",3.21
19,20.,Faded,Alan Walker,"December 3, 2015",3.21
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.20
21,22.,Axel F,Crazy Frog,"June 16, 2009",3.16
22,23.,Bailando,Enrique Iglesias,"April 11, 2014",3.15
23,24.,Let Her Go,Passenger,"July 25, 2012",3.15
24,25.,Lean On,Major Lazer,"March 22, 2015",3.14
25,26.,Shake It Off,Taylor Swift,"August 18, 2014",3.13
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.06
27,28.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.04
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.02
29,30.,Mi Gente,J Balvin,"June 29, 2017",3.02

In [12]:
driver.close()

# 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
    
A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [2]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [3]:
url='https://www.bcci.tv/'
driver.get(url)
time.sleep(5)

In [4]:
search=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a').get_attribute('href')

driver.get(search)
time.sleep(5)

In [5]:
#creating the empty lists
Match_title=[]
Series=[]
Place=[]
Date=[]
Time=[]

In [6]:
#scraping titles of match
tag= driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]')
for i in tag:
    Match_title.append(i.text.split("-")[0])

In [7]:
#scraping Series of match
tag= driver.find_elements_by_xpath('//span[@class="ng-binding"]')
for i in tag:
    Series.append(i.text)

In [8]:
#getting place of match held
tag= driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]')
for i in tag:
    Place.append(i.text.split("-")[1])

In [9]:
#scraping date of match
tag= driver.find_elements_by_xpath('//div[@class="match-card-left match-schedule"]')
for i in tag:
    Date.append(i.text)

In [10]:
#time of match
tag= driver.find_elements_by_xpath('//div[@class="match-card-right match-schedule "]')
for i in tag:
    Time.append(i.text)

In [11]:
#converting the match details into dataframe
df = pd.DataFrame({'Match title':Match_title, 'Series':Series, 'Place':Place, 'Date':Date,'Time':Time})
df

,Match title,Series,Place,Date,Time
0,3rd Test,INDIA TOUR OF SOUTH AFRICA TEST SERIES 2021-22,"Newlands, Cape Town",11 JAN 2022,2:00 PM IST
1,1st ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl",19 JAN 2022,2:00 PM IST
2,2nd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl",21 JAN 2022,2:00 PM IST
3,3rd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Newlands, Cape Town",23 JAN 2022,2:00 PM IST
4,1st ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"NARENDRA MODI STADIUM, Ahmedabad",6 FEB 2022,9:30 AM IST
5,2nd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Sawai Mansingh Stadium, Jaipur",9 FEB 2022,9:30 AM IST
6,3rd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Eden Gardens, Kolkata",12 FEB 2022,9:30 AM IST
7,1st T20I,WEST INDIES TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium, Cuttack",15 FEB 2022,7:30 PM IST

In [12]:
driver.close()

# 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
    

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [23]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-23-f6f558244406>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [24]:
url =  'https://www.guru99.com/'
driver.get(url)

In [25]:
selbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
try:
    selbtn.click() #clicking on Selenium button
except ElementNotInteractableException:
    pass
     
tutbtn =  driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
try: 
    tutbtn.click() #clicking on Exceptions Tutorial button
except ElementNotInteractableException:
    pass

<ipython-input-25-199655db7ae5>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  selbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
<ipython-input-25-199655db7ae5>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  tutbtn =  driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')

In [26]:
Name = []
desc = []

In [27]:
for i in range(2,43):
    Name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
    try:
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
for i in range(2,43):    
    desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")
    try:
        desc.append(desc_tag.text)
    except NoSuchElementException:
        desc.append("-")

<ipython-input-27-3f1864b37f57>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
<ipython-input-27-3f1864b37f57>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")

In [29]:
Excep = {'Name': Name,'Description':desc}
ExceptionDF = pd.DataFrame(Excep)
ExceptionDF

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [37]:
driver.close()

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
    
A) Rank

B) State

C) GSDP

D) GSDP

E) Share

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [2]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-2-f6f558244406>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [3]:
url =  'http://statisticstimes.com/'
driver.get(url)

In [4]:
economy = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))

<ipython-input-4-59230701e06b>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  economy = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")

In [5]:
gdp = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")
try:
    gdp.click()
except ElementNotInteractableException:
    driver.get(gdp.get_attribute('href'))

<ipython-input-5-944fd99c1cd2>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")

In [6]:
gdp = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
try:
    gdp.click()
except ElementNotInteractableException:
    driver.get(gdp.get_attribute('href'))

<ipython-input-6-22a8fc58fd4a>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")

In [7]:
state=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[2]")
    for i in name:
        state.append(i.text)
except NoSuchElementException:
    state.append('N/A')
except StaleElementReferenceException:
    state.append('N/A')

<ipython-input-7-692caede9ebe>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[2]")

In [8]:
rank=[i for i in range(1,len(state)+1)]

In [9]:
gsdp20=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[3]")
    for i in name:
        gsdp20.append(i.text)
except NoSuchElementException:
    gsdp20.append('N/A')
except StaleElementReferenceException:
    gsdp20.append('N/A')

<ipython-input-9-1f802230db96>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[3]")

In [10]:
gsdp19=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[4]")
    for i in name:
        gsdp19.append(i.text)
except NoSuchElementException:
    gsdp19.append('N/A')
except StaleElementReferenceException:
    gsdp19.append('N/A')

<ipython-input-10-1295e0a1f490>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[4]")

In [11]:
share=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[5]")
    for i in name:
        share.append(i.text)
except NoSuchElementException:
    share.append('N/A')
except StaleElementReferenceException:
    share.append('N/A')

<ipython-input-11-e175756bdf71>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[5]")

In [12]:
gdp=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[6]")
    for i in name:
        gdp.append(i.text)
except NoSuchElementException:
    gdp.append('N/A')
except StaleElementReferenceException:
    gdp.append('N/A')

<ipython-input-12-687d4f1ce5be>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[6]")

In [13]:
dataframe=pd.DataFrame()
dataframe['Rank']=rank
dataframe['State']=state
dataframe['GSDP at current price (19-20)']=gsdp20
dataframe['GSDP at current price (18-19)']=gsdp19
dataframe['Share (18-19)']=share
dataframe['GDP ($billion)']=gdp
dataframe.style.hide_index()

In [15]:
driver.close()

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
    
A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [86]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [87]:
url = 'https://github.com/' #getting the required url
driver.get(url)

In [88]:
Trending=driver.find_element_by_xpath("//a[@href='/trending']") #Looking for Trending
driver.get(Trending.get_attribute('href')) #Open Trending page
time.sleep(2) #wait for 2 m.s.

In [89]:
Repository_title = []
Repository_description = []
Contributors_count = []
Language_used = []

In [90]:
for i in range(1,26): #25 repository are trending so running the loop for 1 to 26
    link1 = driver.find_element_by_xpath("//article[@class='Box-row']["+str(i)+"]/h1/a") #Repository Title
    Repository_title.append(link1.text)
    try:
        link2 = driver.find_element_by_xpath("//article[@class='Box-row']["+str(i)+"]/p") #Repository Description
        Repository_description.append(link2.text)
    except NoSuchElementException as e:
        Repository_description.append("-") #If Description is not present add "-"

In [91]:
urls = []
contr=driver.find_elements_by_xpath("//article[@class='Box-row']/h1/a") #Collecting the URLS of each repository
for i in contr:
    urls.append(i.get_attribute('href')) #Added url in urls field

In [92]:
for i in urls:
    driver.get(i) #Open the URL one by one
    time.sleep(2)
    counter = 0
    for i in range(1,6):
        try:
            test = driver.find_element_by_xpath("//div[@class='BorderGrid BorderGrid--spacious']/div["+str(i)+"]/div/h2/a") #Searching for Contributors
            value = test.text
            if(value.find("Contributors") != -1): #If found than
                con = value.split(" ")            #Split value with space
                Contributors_count.append(con[1]) #Second value will be number of Contributors
            else:
                counter += 1
        except NoSuchElementException as e:
            counter += 1
            pass
    if(counter == 5):
        Contributors_count.append("-")           #If no Contributors for that Repository than add "-"
        
    count = 0
    for i in range(1,7):
        try:
            test = driver.find_element_by_xpath("//div[@class='BorderGrid BorderGrid--spacious']/div["+str(i)+"]/div/h2") #Searching for Language Used
            value = test.text
            string = ""
            if(value.find("Languages") != -1): #If Language found than
                lang = driver.find_elements_by_xpath("//div[@class='BorderGrid BorderGrid--spacious']/div["+str(i)+"]/div/ul/li/a/span[1]")
                for i in lang:
                    string = string + i.text + " " #Added all languages one by one
                Language_used.append(string)
            else:
                count += 1
        except NoSuchElementException as e:
            count += 1
            pass
    if(count == 6):
        Language_used.append("-")                 #If no Language found then add "-"

In [93]:
Github = pd.DataFrame({}) #DataFrame
Github['Repository Title'] = Repository_title
Github['Repository Description'] = Repository_description
Github['Contributors Count'] = Contributors_count
Github['Language Used'] = Language_used
Github

,Repository Title,Repository Description,Contributors Count,Language Used
0,Asabeneh / 30-Days-Of-JavaScript,30 days of JavaScript programming challenge is...,18,JavaScript HTML
1,Igglybuff / awesome-piracy,A curated list of awesome warez and piracy links,118,HTML Shell
2,521xueweihan / HelloGitHub,"分享 GitHub 上有趣、入门级的开源项目。Share interesting, entr...",11,Python
3,megadose / holehe,holehe allows you to check if the mail is used...,14,Python
4,alibaba / xquic,-,6,C CMake Shell
5,TheAlgorithms / Python,All Algorithms implemented in Python,-,-
6,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"4,374",JavaScript TypeScript CSS Shell EJS Dockerfile
7,VGVentures / slide_puzzle,-,4,Dart HTML
8,iluwatar / java-design-patterns,Design patterns implemented in Java,270,Java
9,withshepherd / faker.js,-,200,JavaScript
10,lynn / hello-wordl,Wordle clone you can play forever,-,TypeScript CSS HTML
11,TheAlgorithms / Java,All Algorithms implemented in Java,336,Java
12,sunym1993 / flash-linux0.11-talk,你管这破玩意叫操作系统源码 — 像小说一样品读 Linux 0.11 核心代码,14,C HTML Roff E GAP M
13,ibraheemdev / modern-unix,A collection of modern/faster/saner alternativ...,10,-
14,faridrashidi / kaggle-solutions,🏅 Collection of Kaggle Solutions and Ideas 🏅,-,HTML Python CSS Ruby
15,solo-io / bumblebee,Get eBPF programs running from the cloud to th...,8,C Go
16,MichMich / MagicMirror,MagicMirror² is an open source modular smart m...,-,-
17,LaravelDaily / laravel-tips,Awesome tips for Laravel,38,-
18,BookStackApp / BookStack,A platform to create documentation/wiki conten...,145,PHP Blade JavaScript SCSS
19,akullpp / awesome-java,"A curated list of awesome frameworks, librarie...",314,-
20,microsoft / PowerToys,Windows system utilities to maximize productivity,262,C# C++ G-code C PowerShell HLSL
21,kdn251 / interviews,Everything you need to know to get the job.,30,Java
22,ascoders / weekly,前端精读周刊。帮你理解最前沿、实用的技术。,58,JavaScript
23,facebookresearch / mae,PyTorch implementation of MAE https//arxiv.org...,2,Python
24,JumpCrypto / crypto-reading-list,-,2,-

In [94]:
driver.close()

# 6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [2]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [3]:
#Getting the webpage of mentioned url 
url = "https:/www.billboard.com/"
driver.get(url)

In [4]:
#Clicking on charts
driver.find_element_by_xpath("//li[@class='o-nav__list-item lrv-u-align-items-center lrv-u-flex']/a").click()

In [5]:
#clicking on 'Hot 100'
driver.find_element_by_xpath("//a[@class='c-link  lrv-a-unstyle-link lrv-u-color-brand-primary:hover lrv-a-hover-effect lrv-u-whitespace-nowrap lrv-u-color-grey-dark']").click()

In [6]:
#Creating empty lists
Song_Name = []
Artist_Name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [7]:
# Scraping data of song names
for i in driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']"):
    Song_Name.append(i.text)

In [8]:
# Scraping data of artist names
for i in driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']"):
    Artist_Name.append(i.text)

In [9]:
# Scraping data of last week ranks
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']"):
    Last_week_rank.append(i.text)

In [10]:
# Scraping data of peak rank
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']"):
    Peak_rank.append(i.text)

In [11]:
# Scraping data of weeks on board
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']"):
    Weeks_on_board.append(i.text)

In [12]:
# Creating dataframe for scraped data
billboard=pd.DataFrame({})
billboard['Name'] = Song_Name
billboard['Artist'] = Artist_Name
billboard['Last week rank'] = Last_week_rank
billboard['Peak rank'] = Peak_rank
billboard['Weeks on board'] = Weeks_on_board
billboard

Empty DataFrame
Columns: [Name, Artist, Last week rank, Peak rank, Weeks on board]
Index: []

In [13]:
driver.close()

# 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [80]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-80-f6f558244406>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [81]:
# Getting the webpage of mentioned url 
url=('https://www.naukri.com/')
driver.get(url)
time.sleep(2)

In [82]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element_by_xpath("//a[@title='Search Recruiters']")
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

<ipython-input-82-4aaa2a21c395>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  recruiter = driver.find_element_by_xpath("//a[@title='Search Recruiters']")

In [83]:
# Fetching search button, sending keys and clicking on it
search = driver.find_element_by_xpath("//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()     
time.sleep(3)

<ipython-input-83-297c7dfb8bbd>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search = driver.find_element_by_xpath("//div[@class='inpWrap']//input")
<ipython-input-83-297c7dfb8bbd>:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

In [84]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [85]:
#Scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)

<ipython-input-85-67752e7ad5a3>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):

In [86]:
#Scraping data of Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    Designation.append(i.text)
time.sleep(3)

<ipython-input-86-b48c7370ca08>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):

In [87]:
#Scraping data of company name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)
time.sleep(3)

<ipython-input-87-4ef29f7354f8>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):

In [88]:
#scraping data of Skills 
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
    time.sleep(3)

<ipython-input-88-ce48eac17988>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):

In [89]:
#Scraping data of locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

<ipython-input-89-2da63aa87426>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):

In [90]:
# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name[:50]
Naukri['Designation'] = Designation[:50]
Naukri['Company'] = Company[:50]
Naukri['Skills'] = Skills[:50]
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Anik Agrawal
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Company Recruiter
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Ahmedabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",subhas patel
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Founder CEO
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",UK - (london)
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Recruitment Lead Consultant
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Vadodara / Baroda
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Trivandrum
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Asif Lucknowi
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Director
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Indore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",InstaFinancials
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Human Resource
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
30,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Priyanka Akiri
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",HR Manager
32,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Hyderabad
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Kalpana Dumpala
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Executive Hiring
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Hyderabad / Secunderabad
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Mubarak
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Company HR
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Kushal Rastogi
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Company HR
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Mumbai
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Mahesh Babu Channa
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",HR Team Lead
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Sakshi Chhikara
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Assistant Manager HR
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Chandigarh
48,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Kapil Devang
49,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",HR Manager

In [91]:
driver.close()

# 8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
    
A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [35]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-35-f6f558244406>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [36]:
url =  ' https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/'
driver.get(url)

In [37]:
Book= []
Author = []
Volumes = []
Publisher = []
Genre = []

In [38]:
for i in range(1,101):
    try:
        Book_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[2]")
        Book.append(Book_tag.text)
    except NoSuchElementException:
        Book.append("-")

<ipython-input-38-21794a4a5e82>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Book_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[2]")

In [39]:
for i in range(1,101):
    try:
        Author_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[3]")
        Author.append(Author_tag.text)
    except NoSuchElementException:
        Author.append("-")

<ipython-input-39-41d72a5b52b8>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Author_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[3]")

In [40]:
for i in range(1,101):
    try:
        Volumes_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[4]")
        Volumes.append(Volumes_tag.text)
    except NoSuchElementException:
        Volumes.append("-")

<ipython-input-40-db900cab95ed>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Volumes_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[4]")

In [41]:
for i in range(1,101):
    try:
        Publisher_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[5]")
        Publisher.append(Publisher_tag.text)
    except NoSuchElementException:
        Publisher.append("-")

<ipython-input-41-093d416725d1>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Publisher_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[5]")

In [42]:
for i in range(1,101):
    try:
        Genre_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[6]")
        Genre.append(Genre_tag.text)
    except NoSuchElementException:
        Genre.append("-")

<ipython-input-42-68b2b8cb8a01>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Genre_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[6]")

In [43]:
Top100Books = {'Book name': Book,'Author name':Author,'Volumes sold':Volumes,'Publisher':Publisher,'Genre':Genre}

Top100BooksDF = pd.DataFrame(Top100Books)

Top100BooksDF

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [44]:
driver.close()

# 9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [92]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-92-f6f558244406>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [93]:
# Getting the webpage of mentioned url 
url=("https://www.imdb.com/list/ls095964455/")
driver.get(url)

In [94]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

In [95]:
#Scraping data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

<ipython-input-95-dab3ac3aa4e0>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):

In [96]:
#Scraping data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)

<ipython-input-96-8dbaae3f02f1>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):

In [97]:
#Scraping data of genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)

<ipython-input-97-65107dadfaa9>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='genre']"):

In [98]:
#Scraping data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)

<ipython-input-98-2706123df310>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='runtime']"):

In [99]:
#Scraping data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)

<ipython-input-99-65cea6fd3eb9>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):

In [100]:
#Scraping data of votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

<ipython-input-100-a381af2c6a35>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):

In [101]:
# Creating dataframe for scraped data
TV_series=pd.DataFrame({})
TV_series['Name'] = Name
TV_series['Year Span'] = Year_span
TV_series['Genre'] = Genre
TV_series['Run Time'] = Run_time
TV_series['Ratings'] = Ratings
TV_series['Votes'] = Votes
TV_series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,925,834"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"948,602"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"920,661"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"275,750"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"236,045"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,064"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,845"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"182,578"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"38,145"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"217,220"

In [102]:
driver.close()

# 10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
    
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

In [57]:
driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-57-f6f558244406>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/91897/Downloads/chromedriver_win32/chromedriver.exe")

In [58]:
url =  'https://archive.ics.uci.edu/'
driver.get(url)

In [59]:
dtbtn = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a') #view all data sets button
try:
    dtbtn.click() #clicking on view all data sets button
except ElementNotInteractableException:
    pass

<ipython-input-59-2953cdfaaa09>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dtbtn = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a') #view all data sets button

In [60]:
Name = []
Datatype = []
Task = []
Attribute = []
instances = []
attribute_no = []
Year = []

In [61]:
for i in range(1,590):
    try:
        Name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")

<ipython-input-61-fcd65c110d0c>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")

In [62]:
for i in range(1,590):
    try:
        Datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
        Datatype.append(Datatype_tag.text)
    except NoSuchElementException:
        Datatype.append("-")

<ipython-input-62-6433648bd036>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")

In [63]:
for i in range(1,590):
    try:
        Task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
        Task.append(Task_tag.text)
    except NoSuchElementException:
        Task.append("-")

<ipython-input-63-288ebfd67a96>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")

In [64]:
for i in range(1,590):
    try:
        Attribute_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
        Attribute.append(Attribute_tag.text)
    except NoSuchElementException:
        Attribute.append("-")

<ipython-input-64-68ed0eed8ab7>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Attribute_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")

In [65]:
for i in range(1,590):
    try:
        instances_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
        instances.append(instances_tag.text)
    except NoSuchElementException:
        instances.append("-")

<ipython-input-65-50489e4d65c5>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  instances_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")

In [66]:
for i in range(1,590):
    try:
        attribute_no_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
        attribute_no.append(attribute_no_tag.text)
    except NoSuchElementException:
        Votes.append("-")

<ipython-input-66-bdec62074f4c>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  attribute_no_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")

In [67]:
for i in range(1,590):
    try:
        Year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")
        Year.append(Year_tag.text)
    except NoSuchElementException:
        Year.append("-")

<ipython-input-67-6585a2dc9f66>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")

In [68]:
len(Task)

589

In [69]:
repositories = {'Dataset name': Name,'Data type':Datatype,'Task':Task,'Attribute type':Attribute,'No of instances':instances,'No of attribute':attribute_no,'Year':Year}

repositoriesDF = pd.DataFrame(repositories)

repositoriesDF.drop(index = 0,inplace = True)
repositoriesDF

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
584,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
585,Gait Classification,Multivariate,Classification,Real,48,321,2020
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
588,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021

In [70]:
driver.close()